import "../globals.css";
import Navbar from "@/components/navbar";
import Provider from "@/components/providers";
import { Metadata } from "next";
import { getAuthSession } from "./api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Eventory",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getAuthSession();

  return (
    <html lang="en">
      <body className="antialiased">
        <main>
          <Provider>
            {session && <Navbar />}
            {children}
          </Provider>
        </main>
      </body>
    </html>
  );
}
