import "../globals.css";
import Navbar from "@/components/navbar";
import Provider from "@/components/providers";
import { getUserId } from "@/lib/server/user";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userId = await getUserId();

  return (
    <html lang="en">
      <body className="antialiased">
        <main>
          <Provider>
            {userId && <Navbar />}
            {children}
          </Provider>
        </main>
      </body>
    </html>
  );
}
